### PR TITLE
Ported wayk-cse-patcher to Linux

### PR DESCRIPTION
**Pull request by RRRadicalEdward**
I have ported wayk-cse-patched to Linux. I replaced the usage of the rcedit library that patched WaykCSE's resources with lief-rs the same API.

### CODE REVIEW

**Review by awakecoding — COMMENTED** [review]
it builds on both Windows and Linux (I updated the commit reference in lief-rs) but cargo test fails on Linux due to the missing code signing executable. If you could just update this branch to fix the conflict + disable the test for code signing on Linux for now, it would be good for a merge.

**Comment by awakecoding** [comment]
@thenextman maybe take a look at it to see if it's going to break anything with our recent changes that we made.

**Comment by thenextman** [comment]
I didn't see any issue with the changes; but why did we lose the build script? I don't see how the WaykCse.exe is compiled anymore?

**Comment by RRRadicalEdward** [comment]
> I didn't see any issue with the changes; but why did we lose the build script? I don't see how the WaykCse.exe is compiled anymore?

WaykCSE contains WinAPI so wayk-cse-patched with build.rs that compiles WaykCSE and cannot be run on Linux. For now, WaykCSE will be passed to wayk-cse-patcher as a CLI argument. WaykCSE still can be compiled by CMake on Windows and then used on Windows or Linux.

**Comment by RRRadicalEdward** [comment]
> it builds on both Windows and Linux (I updated the commit reference in lief-rs) but cargo test fails on Linux due to the missing code signing executable. If you could just update this branch to fix the conflict + disable the test for code signing on Linux for now, it would be good for a merge.

Done 🙂

**Comment by thenextman** [comment]
LGTM

**Comment by awakecoding** [comment]
@RRRadicalEdward can you rebase the branch and resolve the branch conflicts so we can merge it?

**Comment by RRRadicalEdward** [comment]
> @RRRadicalEdward can you rebase the branch and resolve the branch conflicts so we can merge it?

**Comment by RRRadicalEdward** [comment]
> @RRRadicalEdward can you rebase the branch and resolve the branch conflicts so we can merge it?

@awakecoding Yes. The porting-to-linux branch is already on the latest master and I have resolved merge conflicts.

**Comment by awakecoding** [comment]
@RRRadicalEdward the build fails on Windows:

`Compiling wayk-cse-patcher v0.1.5 (C:\__w\88\s\wayk-cse-patcher)
warning: unused import: `File`
 --> wayk-cse-patcher\src\bundle.rs:3:16
  |
3 |     fs::{self, File},
  |                ^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `ArtifactsBundle`
  --> wayk-cse-patcher\src\bundle.rs:12:37
   |
12 | use crate::artifacts_bundle::{self, ArtifactsBundle};
   |                                     ^^^^^^^^^^^^^^^

error[E0599]: no variant named `WaykBinaries` found for enum `BundlePackageType`
  --> wayk-cse-patcher\src\patcher.rs:66:36
   |
66 |                 BundlePackageType::WaykBinaries { bitness: *bitness },
   |                                    ^^^^^^^^^^^^ variant not found in `BundlePackageType`
   | 
  ::: wayk-cse-patcher\src\bundle.rs:43:1
   |
43 | pub enum BundlePackageType {
   | -------------------------- variant `WaykBinaries` not found here

error: aborting due to previous error; 2 warnings emitted

`

**Comment by RRRadicalEdward** [comment]
> @RRRadicalEdward the build fails on Windows:
> 
> `Compiling wayk-cse-patcher v0.1.5 (C:\__w\88\s\wayk-cse-patcher) warning: unused import: `File`--> wayk-cse-patcher\src\bundle.rs:3:16 | 3 | fs::{self, File}, | ^^^^ | = note:`#[warn(unused_imports)]` on by default
> 
> warning: unused import: `ArtifactsBundle`
> --> wayk-cse-patcher\src\bundle.rs:12:37
> |
> 12 | use crate::artifacts_bundle::{self, ArtifactsBundle};
> | ^^^^^^^^^^^^^^^
> 
> error[E0599]: no variant named `WaykBinaries` found for enum `BundlePackageType`
> --> wayk-cse-patcher\src\patcher.rs:66:36
> |
> 66 | BundlePackageType::WaykBinaries { bitness: *bitness },
> | ^^^^^^^^^^^^ variant not found in `BundlePackageType`
> |
> ::: wayk-cse-patcher\src\bundle.rs:43:1
> |
> 43 | pub enum BundlePackageType {
> | -------------------------- variant `WaykBinaries` not found here
> 
> error: aborting due to previous error; 2 warnings emitted
> 
> `

@awakecoding  I did a mistake with rebase. I have fixed it and it should work.

**Comment by RRRadicalEdward** [comment]
> @RRRadicalEdward can you rebase the branch and resolve the branch conflicts so we can merge it?

@awakecoding  Done 🙂

**Review by awakecoding — APPROVED** [review]
LGTM

**Pull request merged**
